// Do not display overflow warnings generated by type conversions
#![allow(overflowing_literals)]

fn main() {
    let decimal = 65.4321_f32;

    // mistake! Does not provide implicit conversions
    // let integer: u8 = decimal;
    // Correction ^ Comment out this line

    // Conversions can be displayed
    let integer = decimal as u8;
    let character = integer as char;

    println!("Casting: {} -> {} -> {}", decimal, integer, character);

    // When converting any type system to unsigned type T, constant additions or subtractions are made (std::T::MAX + 1)
    // until the value is within the range of the new type T

    // 1000 is already within the range of u16
    println!("1000 as a u16 is: {}", 1000 as u16);

    // 1000 -256 - 256 - 256 = 232
    // The actual processing method is: save starting from the least significant bits (LSB, least significant bits)
    // 8 bits, then the remaining positions up to the most significant bits (MSB) are discarded.
    // Note: MSB is the highest bit of binary, and LSB is the lowest bit of binary. According to daily writing habits, it is the leftmost digit and the rightmost digit.
    println!("1000 as a u8 is : {}", 1000 as u8);
    // -1 + 256 = 255
    println!("  -1 as a u8 is: {}", (-1i8) as u8);

    // For positive numbers, this is the same as taking modulo
    println!("1000 mod 256 is: {}", 1000 % 256);

    // When converting to a signed type, the result (of the bit operation) is the same as "convert to the corresponding unsigned type first, and if the MSB is 1, then the value is negative"

    // Of course, if the value is already within the range of the target type, just put it in directly.
    println!(" 128 as a i16 is: {}", 128 as i16);
    // Converting 128 to u8 is still 128, but converting to i8 is equivalent to taking the eight-bit two's complement of 128, and its value is:
    println!(" 128 as a i8 is: {}", 128 as i8);

    // Repeat previous example
    // 1000 as u8 -> 232
    println!("1000 as a u8 is: {}", 1000 as u8);
    // The two's complement of 232 is -24
    println!(" 232 as a i8 is: {}", 232 as i8);
}