/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function hello(): string
export declare function concatStr(a: string, b: string): string
export interface ToolOptions {
  id: number
  name: string
}
export declare function getOptions(options: ToolOptions): ToolOptions
export declare function asyncFib(input: number): Promise<string>
export declare function callThreadsafeFunction(callback: (err: null | Error, result: number) => void): void
