[package]
name = "gen_locale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.19"
clap = { version = "4.1", features = ["derive", "cargo"] }