CREATE TABLE accounts (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (
        CURRENT_TIMESTAMP AT TIME ZONE 'UTC'
    ),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (
        CURRENT_TIMESTAMP AT TIME ZONE 'UTC'
    )
);